package:
  name: linux
  version: 4.9.58
  description: Linux kernel
  license: [GPL2]

  source:
    - https://cdn.kernel.org/pub/$name/kernel/v4.x/$name-$version.tar.xz
    - config

  prepare:
    - mkdir -p "${builddir}"/build
    - cp config "${builddir}"/build/.config
    - make -C "${builddir}/${name}-${version}" O="${builddir}/build" ARCH="x86_64" silentoldconfig

  build:
    - cd build && make ARCH=x86_64 CC=gcc KBUILD_BUILD_VERSION="${version}-Mesalock" bzImage

  install:
    - install -Dm644 build/arch/x86_64/boot/bzImage "$pkgdir"/boot/vmlinuz
