#!/bin/busybox sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t devtmpfs devtmpfs /dev
# mount -t devpts devpts /dev/pts
# mount -t tmpfs tmpfs /dev/shm
# 
mknod /dev/console c 5 1
mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/urandom c 1 9

/bin/mgetty &
wait
